model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"

# sandbox_mode = "workspace-write"
network_access = true
web_search = "live"
personality = "pragmatic"

[features]
shell_snapshot = true
multi_agent = true
apps = true

[tui]
notifications = true

# [mcp_servers.context7]
# command = "npx"
# args = ["-y", "@upstash/context7-mcp"]

# [mcp_servers.sequential-thinking]
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

# [mcp_servers.serena]
# command = "uvx"
# args = [
#   "--from",
#   "git+https://github.com/oraios/serena",
#   "serena",
#   "start-mcp-server",
#   "--context",
#   "codex",
# ]

# [mcp_servers.chrome-devtools]
# command = "npx"
# args = ["chrome-devtools-mcp@latest"]
