[tools]
go = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
python = "latest"
stylua = "2.3.1"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
